canonifyURLs = true
baseURL = "https://jorgen-am.github.io/varebil-leasing/"
locale = 'nb-no'
title = 'Varebil leasing'
publishDir = "public"
port = 1316

# Utdataformater for forsiden (Genererer index.json på roten)
[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  post = "/post/:title/"
  biler = "/biler/:slug/"
  
[taxonomies]
  drivlinje = "drivlinje"
  gir = "gir"
  trekk = "trekk"
  biltype = "biltype"

[menu]
  # --- TOPPMENY (main) ---
  [[menu.main]]
    identifier = "Biler"
    name = "Våre biler"
    url = "/biler/"
    weight = 8

  [[menu.main]]
    name = "Kundeomtaler"
    url = "/omtaler/"
    weight = 30

  [[menu.main]]
    name = "Artikler"
    url = "/post/"
    weight = 31

  [[menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 40

  [[menu.main]]
    name = "Tjenester"
    identifier = "tjenester"
    url = "/tjenester/"
    weight = 3

  [[menu.main]]
      name = "Leasing"
      parent = "tjenester"
      url = "/tjenester/leasing/"
      weight = 1

  [[menu.main]]
      name = "Forsikring"
      parent = "tjenester"
      url = "/tjenester/forsikring/"
      weight = 2

  [[menu.main]]
      name = "Releasing"
      parent = "tjenester"
      url = "/tjenester/releasing/"
      weight = 3

  [markup.goldmark.renderer]
    unsafe = true